### ISSUE TITLE
CTU-50 PCAPs available?

### ISSUE THREAD

**Issue by rickhg12hs** [stratosphereips/ml-detectors-ctu-50#2]
Are the CTU-50 dataset PCAPs available?

If anonymization is required, could it be done such that IP address re-assignment, etc., is consistent and maintains subnet relations throughout the entire dataset?

Regards.

**Comment by eldraco** [comment]
Hi @rickhg12hs sorry for the delay in answering.
Due to the nature of how CTU-50 was created, there are only pcaps for the malware traffic but not for the benign traffic. This is because that traffic was captured using Zeek and therefore there are only flows. 
In the final publication of CTU-50, there will be only flows in Zeek file format.

The malware traffic used can be found here. (as individual captures, and not curated for ctu-50)
Go here https://mcfp.felk.cvut.cz/publicDatasets/, and then the folders:

- CTU-Malware-Capture-Botnet-346-1
- CTU-Malware-Capture-Botnet-327-2
- CTU-Malware-Capture-Botnet-230-1
- CTU-Malware-Capture-Botnet-67-1
- CTU-Malware-Capture-Botnet-219-2
